version: "3.7"
services:
  nodered:
    image: mokojarasi/node-red-io-magazine
    ports:
      - 1880:1880
    logging:
      driver: "json-file"
      options:
        max-size: "20k"
        max-file: "3"
  facial-age-estimator:
    image: codait/max-facial-age-estimator
    ports:
      - 5000:5000
    logging:
      driver: "json-file"
      options:
        max-size: "20k"
        max-file: "3"
  facial-emotion-classifier:
    image: codait/max-facial-emotion-classifier
    logging:
      driver: "json-file"
      options:
        max-size: "20k"
        max-file: "3"
